### ISSUE TITLE
add meta name="description + keywords"

### ISSUE THREAD

**Issue by susaninivan** [mvchn/booking#135]
add meta name="description + keywords"

https://scriptorium.cloud/
https://scriptorium.cloud/cards/397fd456-d386-4f8e-ab60-71c74ed4cb7d
https://scriptorium.cloud/search?isbn=222

![изображение](https://user-images.githubusercontent.com/32177921/124099134-e1d02a00-da65-11eb-81cb-6c6c04170b02.png)

**Comment by mvchn** [comment]
meta keywords tag is not valid to Google
